repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.3.0
    hooks:
    -   id: nixpkgs-fmt
-   repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
    -   id: stylua
